name: Run QA Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install Playwright browsers
          playwright install

      - name: Run UI Tests
        run: |
          pytest tests/ui --maxfail=1 --disable-warnings --junitxml=ui-test-results.xml
        continue-on-error: false

      - name: Debug token
        run: echo "Token first 4 chars: ${GOREST_TOKEN:0:4}"
        env:
          GOREST_TOKEN: ${{ secrets.GOREST_TOKEN }}

      - name: Run API Tests
        run: |
          pytest tests/api --maxfail=1 --disable-warnings --junitxml=api-test-results.xml
        env:
          GOREST_TOKEN: ${{ secrets.GOREST_TOKEN }}
        continue-on-error: false

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QA-Test-Reports
          path: |
            ui-test-results.xml
            api-test-results.xml
            tests/ui/*.png